version: '2.1'

services:
  collectd:
    image: sungardas/logcabin-docker:latest
    environment:
      LOGCABIN_HOST: 
      API_KEY: 
      COOKIE_SECRET: 
      CLIENT_ID: 
      CLIENT_SECRET: 
      ALLOWED_DOMAIN: 
    restart: on-failure
    stop_grace_period: 10s

